module.exports = {
    ADDTAB: 'ADDTAB',
    REMOVETAB: 'REMOVETAB',
    CLEARTAB: 'CLEARTAB',
    UPDATEACCOUNT: 'UPDATEACCOUNT',
    UPDATENAVLISTS: 'UPDATENAVLISTS',
    CLEARNAVLISTS: 'CLEARNAVLISTS'
};